import { isValidPhoneNumber } from "libphonenumber-js";
import { toPostgresTimestampUTC } from "../../helper/timestampFunctions";
import type { GenericUserPhoneArgs } from "../../typedefs/GenericUserPhoneArgs";
import { v4 as uuidv4 } from 'uuid';
import { failure, success, type DataErrorReturnObject } from "dataerror";
import type { UserSessionObject } from "../../typedefs/UserSessionObject";
import { mockabaseErrors } from "../../data/mockabaseErrors";
import { blankSession } from "../../data/blankObjects";
import db from "../db";
import type { User } from "../../typedefs/User";
import type { MockabaseUserReturnObject } from "../../typedefs/MockabaseUserReturnObject";
import { generateRandomOTP } from "../../helper/generateRandomOTP";

interface PhoneSignupArgs extends GenericUserPhoneArgs {
  id?: string;
}

const phoneSignup = async (args: PhoneSignupArgs) => {
  const { phoneNumber } = args;

  const id = args.id ? args.id : uuidv4();
  const createdAt = toPostgresTimestampUTC(new Date());
  const updatedAt = toPostgresTimestampUTC(new Date());

  if (!isValidPhoneNumber(phoneNumber)) {
    return await failure<UserSessionObject>(mockabaseErrors.invalidPhoneNumber, 'models/phoneSignup');
  }

  // no reason not to assign OTP within the signup function that I can see currently - no OTP e-mail is generated by Mockabase
  const otp = generateRandomOTP(6);

  try {
    const query = db.prepare('INSERT INTO users (id, phone_number, otp, created_at, updated_at) VALUES (?, ?, ?, ?, ?) RETURNING id, email, phone_number AS "phoneNumber", oauth_provider AS "oauthProvider";');
    const result = query.run(id, phoneNumber, otp, createdAt, updatedAt);

    const data: UserSessionObject = result ? { session: { id, email: null, phoneNumber, providerType: 'phone', oauthProvider: null } } : { session: blankSession };
    return await success<UserSessionObject>(data);
  } catch (error) {
    return await failure<UserSessionObject>(error, 'models/phoneSignup');
  }
}

const phoneLogin = async (args: GenericUserPhoneArgs): Promise<MockabaseUserReturnObject> => {
  const { phoneNumber } = args;

  if (!isValidPhoneNumber(phoneNumber)) {
    return await failure<UserSessionObject>(mockabaseErrors.invalidPhoneNumber, 'models/phoneSignup');
  }

  try {
    const userResponse = await getUserByPhone(phoneNumber);

    if (userResponse.error && userResponse.error.code == 'user_not_found') {
      return await failure<UserSessionObject>(mockabaseErrors.userNotFound, 'models/phone/phoneLogin');
    }

    const user = userResponse.data!;

    // return an error if this is attempted with no OTP
    if (!user.otp) {
      return await failure<UserSessionObject>(mockabaseErrors.missingOTP, 'models/phoneAuth/phoneLogin');
    }

    return await success<UserSessionObject>({ session: { id: user.id, email: null, phoneNumber: user.phoneNumber!, providerType: 'phone', oauthProvider: null } });
  } catch (error) {
    return await failure<UserSessionObject>(error, 'models/phone/phoneLogin');
  }
}

const getUserByPhone = async (phoneNumber: string): Promise<DataErrorReturnObject<User>> => {
  try {
    const query = db.prepare('SELECT id, email, phone_number AS "phoneNumber", provider_type AS "providerType", encrypted_password AS "encryptedPassword", otp FROM users WHERE phone_number = ?');
    const result = query.get(phoneNumber);
    const user: User | undefined = result as User | undefined; // Type assertion for safety

    if (!user || user.id === '') {
      return await failure<User>(mockabaseErrors.userNotFound, 'models/phoneAuth/getUserByPhone');
    }

    return await success<User>(user);
  } catch (error) {
    return await failure<User>(error, 'models/phoneAuth/emailPasswordLogin');
  }
}

export {
  phoneSignup,
  phoneLogin,
  getUserByPhone
}