import { isValidPhoneNumber } from "libphonenumber-js";
import { toPostgresTimestampUTC } from "../../helper/timestampFunctions";
import type { GenericUserPhoneArgs } from "../../typedefs/GenericUserPhoneArgs";
import { v4 as uuidv4 } from 'uuid';
import { failure, success, type DataErrorReturnObject } from "dataerror";
import type { UserSessionObject } from "../../typedefs/UserSessionObject";
import { mockabaseErrors } from "../../data/mockabaseErrors";
import { blankSession } from "../../data/blankObjects";
import db from "../db";
import { users } from "../schema.js";
import { eq } from "drizzle-orm";
import type { User } from "../../typedefs/User";
import type { MockabaseUserReturnObject } from "../../typedefs/MockabaseUserReturnObject";
import { generateRandomOTP } from "../../helper/generateRandomOTP";
import type { PhoneSignupArgs } from "../../typedefs/PhoneSignupArgs";
import { assignOtp } from "./otp";

const phoneSignup = async (args: PhoneSignupArgs) => {
  const { phoneNumber } = args;

  const userExists = await checkUserExistsByPhone(phoneNumber);

  if (userExists) {
    return await failure<UserSessionObject>(mockabaseErrors.userAlreadyExists, 'models/phone/phoneSignup');
  }

  const id = args.id ? args.id : uuidv4();
  const createdAt = toPostgresTimestampUTC(new Date());
  const updatedAt = toPostgresTimestampUTC(new Date());

  // TODO: this was invalidating valid phone numbers.  look into this later
  // if (!isValidPhoneNumber(phoneNumber)) {
  //   return await failure<UserSessionObject>(mockabaseErrors.invalidPhoneNumber, 'models/phoneSignup');
  // }

  // no reason not to assign OTP within the signup function that I can see currently - no OTP e-mail is generated by Mockabase
  const otp = args.staticOTP ? args.staticOTP : generateRandomOTP(6);

  try {
    const result = db.insert(users).values({ id, phoneNumber, otp, createdAt, updatedAt }).run();

    const data: UserSessionObject = result ? { session: { id, email: null, phoneNumber, providerType: 'phone', oauthProvider: null } } : { session: blankSession };
    return await success<UserSessionObject>(data);
  } catch (error) {
    return await failure<UserSessionObject>(error, 'models/phoneSignup');
  }
}

const phoneLogin = async (args: GenericUserPhoneArgs): Promise<MockabaseUserReturnObject> => {
  const { phoneNumber } = args;

  // TODO: this was invalidating valid phone numbers.  look into this later
  // if (!isValidPhoneNumber(phoneNumber)) {
  //   return await failure<UserSessionObject>(mockabaseErrors.invalidPhoneNumber, 'models/phoneSignup');
  // }

  try {
    const userResponse = await getUserByPhone(phoneNumber);

    if (userResponse.error) {
      return await failure<UserSessionObject>(userResponse.error, 'models/phone/phoneLogin');
    }

    if (!userResponse.data) {
      return await failure<UserSessionObject>(mockabaseErrors.userNotFound, 'models/phone/phoneLogin');
    }

    const user = userResponse.data!;

    // return an error if this login is attempted while the user has an active unverified OTP
    if (user.otp) {
      return await failure<UserSessionObject>(mockabaseErrors.invalidOTP, 'models/phoneAuth/phoneLogin');
    }

    // assign a new random OTP to block login without OTP next time
    await assignOtp({ providerType: 'phone', phoneNumber });

    return await success<UserSessionObject>({ session: { id: user.id, email: null, phoneNumber: user.phoneNumber!, providerType: 'phone', oauthProvider: null } });
  } catch (error) {
    return await failure<UserSessionObject>(error, 'models/phone/phoneLogin');
  }
}

const getUserByPhone = async (phoneNumber: string): Promise<DataErrorReturnObject<User>> => {
  try {
    const result = db.select({
      id: users.id,
      email: users.email,
      phoneNumber: users.phoneNumber,
      providerType: users.providerType,
      encryptedPassword: users.encryptedPassword,
      otp: users.otp,
    }).from(users).where(eq(users.phoneNumber, phoneNumber)).all();
    const user: User | undefined = result[0] as User | undefined;

    if (!user || user.id === '') {
      return await failure<User>(mockabaseErrors.userNotFound, 'models/phoneAuth/getUserByPhone');
    }

    return await success<User>(user);
  } catch (error) {
    return await failure<User>(error, 'models/phoneAuth/emailPasswordLogin');
  }
}

const checkUserExistsByPhone = async (phoneNumber: string): Promise<boolean> => {
  try {
    const result = db.select({ phoneNumber: users.phoneNumber }).from(users).where(eq(users.phoneNumber, phoneNumber)).all();

    return result.length > 0;
  } catch (error) {
    console.error(error);
    return false;
  }
}

export {
  phoneSignup,
  phoneLogin,
  getUserByPhone,
  checkUserExistsByPhone
}
